name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Create database
      run: docker volume create --name quotes_db
    - name: Build all images in the docker-compose file
      run: docker compose build
